### ISSUE TITLE
Compiling with -Os breaks interrupt handlers

### ISSUE THREAD

**Issue by VikingAlucard** [isapol/kernel#2]
Observed by @isapol

**Comment by isapol** [comment]
This is a known issue, and is due to the use of inline assembly to hack in our own prologue and epilogue for interrupt handlers (e.g. so that the compiler emits `iret` instead of `ret` etc.). The code just haphazardly hopes that these ASM blocks stay in the correct location relative to the standard prologue and epilogue - i.e. that the `iret` just *happens* to be placed before the standard `ret`. 

Obviously this is terrible and the compiler's optimiser understandably punishes us for it.

Furthermore, GCC did/does not support naked functions on x86-32, which would have omitted the standard prologue and epilogue. I would have been inclined to use `__attribute__((interrupt))`, but GCC again did/does not support this on x86-32. *However, do note that I wrote this code 3 years ago and that GCC may now support one or both of these.*

A preferable alternative is to just write the interrupt handlers in assembly and then thunk into our C code. I do that with [my x86-64 kernel](https://github.com/isapol/kernel64), having learnt from this mistake here.
